/**
 * Zustand store for managing deterioration alerts.
 *
 * Holds the current set of Q-ADDS alerts generated by the alert engine,
 * tracks which alert is actively displayed in the AlertDialog, and
 * provides actions for acknowledging and clearing alerts.
 */

import { create } from 'zustand'
import type { AlertData } from '@/services/alertEngine'

interface AlertState {
  /** All current alerts (acknowledged and unacknowledged) */
  alerts: AlertData[]
  /** The alert currently displayed in the AlertDialog, or null */
  activeAlert: AlertData | null

  /** Append new alerts to the store */
  addAlerts: (alerts: AlertData[]) => void
  /** Mark a specific alert as acknowledged by its id */
  acknowledgeAlert: (id: string) => void
  /** Remove all alerts from the store */
  clearAlerts: () => void
  /** Set the alert to display in the AlertDialog (or null to close) */
  setActiveAlert: (alert: AlertData | null) => void
}

export const useAlertStore = create<AlertState>()((set) => ({
  alerts: [],
  activeAlert: null,

  addAlerts: (newAlerts) =>
    set((state) => ({
      alerts: [...state.alerts, ...newAlerts],
    })),

  acknowledgeAlert: (id) =>
    set((state) => ({
      alerts: state.alerts.map((a) =>
        a.id === id ? { ...a, acknowledged: true } : a,
      ),
      activeAlert:
        state.activeAlert?.id === id
          ? { ...state.activeAlert, acknowledged: true }
          : state.activeAlert,
    })),

  clearAlerts: () => set({ alerts: [], activeAlert: null }),

  setActiveAlert: (alert) => set({ activeAlert: alert }),
}))
